export const vegProducts = [
  { slug: 'hash-browns', name: 'Hash Browns', desc: 'A masterpiece of crispiness and flavor, perfect for breakfast or any time you crave a satisfying crunch.', img: '/images/products/hash-browns.jpg' },
  { slug: 'veg-nuggets', name: 'Veg Nuggets', desc: 'Vegetarian indulgence combining garden-fresh vegetables with a delightful crunch.', img: '/images/products/veg-nuggets.jpg' },
  { slug: 'cheese-corn-nuggets', name: 'Cheese Corn Nuggets', desc: 'Seasoned and shaped into bite-sized pieces, fried golden and crispy.', img: '/images/products/cheese-corn-nuggets.jpg' },
  { slug: 'french-fries', name: 'French Fries', desc: 'Classic yet extraordinary — redefining the standard for taste and texture.', img: '/images/products/french-fries.jpg' },
  { slug: 'crinkle-cut-fries', name: 'Crinkle Cut Fries', desc: 'Crispy on the outside, fluffy on the inside.', img: '/images/products/crinkle-cut-fries.jpg' },
  { slug: 'carrot-fries', name: 'Carrot Fries', desc: 'Nourishing meets delicious — a guilt-free twist on the classic fry.', img: '/images/products/carrot-fries.jpg' },
  { slug: 'veg-samosa', name: 'Veg Samosa', desc: 'A medley of vegetables and authentic spices in a golden envelope of crispiness.', img: '/images/products/veg-samosa.jpg' },
  { slug: 'veg-cheese-samosa', name: 'Veg Cheese Samosa', desc: 'The richness of cheese combined with spices, in a perfect samosa triangle.', img: '/images/products/veg-cheese-samosa.jpg' },
  { slug: 'punjabi-samosa', name: 'Punjabi Samosa', desc: 'Bold, robust flavors of Punjab — a spicier filling in a crispy pastry.', img: '/images/products/punjabi-samosa.jpg' },
  { slug: 'corn-cheese-samosa', name: 'Corn & Cheese Samosa', desc: 'The sweetness of corn and the decadence of cheese, a fusion delight.', img: '/images/products/corn-cheese-samosa.jpg' },
  { slug: 'mexican-samosa', name: 'Mexican Samosa', desc: 'An international adventure — cheese and spices in perfect harmony.', img: '/images/products/mexican-samosa.jpg' },
  { slug: 'paneer-samosa', name: 'Paneer Samosa', desc: "India's culinary heritage — stuffed with aromatic paneer and spices.", img: '/images/products/paneer-samosa.jpg' },
  { slug: 'chilli-cheese-samosa', name: 'Chilli Cheese Samosa', desc: 'Spice-infused cheese filling in our signature crispy pastry.', img: '/images/products/chilli-cheese-samosa.jpg' },
  { slug: 'samosa-patti-veg', name: 'Samosa Patti', desc: 'The foundation of our samosa creations — thin, durable, versatile.', img: '/images/products/samosa-patti.jpg' },
  { slug: 'veg-spring-roll', name: 'Veg Spring Roll', desc: 'Freshness of vegetables and the crunch of perfectly fried wrappers.', img: '/images/products/veg-spring-roll.jpg' },
  { slug: 'puranpoli', name: 'Puranpoli', desc: 'A sweet, flavorful lentil-filled Indian flatbread that brings families together.', img: '/images/products/puranpoli.jpg' },
  { slug: 'mix-veg-paratha', name: 'Mix Veg Paratha', desc: 'Finely chopped vegetables and aromatic spices, handcrafted with care.', img: '/images/products/mix-veg-paratha.jpg' },
  { slug: 'aloo-paratha', name: 'Aloo Paratha', desc: 'Stuffed with spiced mashed potatoes — a comforting North Indian classic.', img: '/images/products/aloo-paratha.jpg' },
  { slug: 'malabar-paratha', name: 'Malabar Paratha', desc: 'Flaky layers celebrating the taste and texture of South India.', img: '/images/products/malabar-paratha.jpg' },
  { slug: 'lachha-paratha', name: 'Lachha Paratha', desc: 'Thin, layered, and utterly delicious — elegance in every bite.', img: '/images/products/lachha-paratha.jpg' },
  { slug: 'paneer-paratha', name: 'Paneer Paratha', desc: 'Flavorful paneer and aromatic spices for a truly decadent meal.', img: '/images/products/paneer-paratha.jpg' },
  { slug: 'aloo-tikki', name: 'Aloo Tikki', desc: 'A symphony of spices and potatoes, shallow-fried to a perfect crisp.', img: '/images/products/aloo-tikki.jpg' },
  { slug: 'veg-burger-patty', name: 'Veg Burger Patty', desc: 'Premium vegetables and spices — a savory foundation for any burger.', img: '/images/products/veg-burger-patty.jpg' },
];

export const nonVegProducts = [
  { slug: 'chicken-cheese-finger', name: 'Chicken Cheese Finger', desc: 'Tender chicken and creamy cheese in a crispy outer layer.', img: '/images/products/chicken-cheese-finger.jpg' },
  { slug: 'chicken-cheese-ball', name: 'Chicken Cheese Ball', desc: 'Bite-sized delights bursting with chicken and cheese flavor.', img: '/images/products/chicken-cheese-ball.jpg' },
  { slug: 'chicken-shami-kabab', name: 'Chicken Shami Kabab', desc: 'Minced chicken, lentils, and aromatic spices — traditional with a twist.', img: '/images/products/chicken-shami-kabab.jpg' },
  { slug: 'chicken-seekh-kabab', name: 'Chicken Seekh Kabab', desc: 'Smoky, skewered, spiced chicken cooked to perfection.', img: '/images/products/chicken-seekh-kabab.jpg' },
  { slug: 'chicken-hara-kabab', name: 'Chicken Hara Kabab', desc: 'Tender chicken with fresh green herbs — flavorful and healthy.', img: '/images/products/chicken-hara-kabab.jpg' },
  { slug: 'chicken-samosa', name: 'Chicken Samosa', desc: 'A classic triangular pastry filled with succulent chicken and spices.', img: '/images/products/chicken-samosa.jpg' },
  { slug: 'chicken-cheese-samosa', name: 'Chicken Cheese Samosa', desc: 'A fusion of chicken, cheese, and spices in a crispy shell.', img: '/images/products/chicken-cheese-samosa.jpg' },
  { slug: 'chicken-spring-roll', name: 'Chicken Spring Roll', desc: 'Tender chicken, crunchy vegetables, and savory spices rolled thin.', img: '/images/products/chicken-spring-roll.jpg' },
  { slug: 'mutton-spice-grill-burger', name: 'Mutton Spice Grill Burger', desc: 'A juicy mutton patty infused with aromatic spices in a soft bun.', img: '/images/products/mutton-spice-grill-burger.jpg' },
  { slug: 'mutton-seekh-kabab', name: 'Mutton Seekh Kabab', desc: 'Minced mutton and a blend of spices, skewered and grilled.', img: '/images/products/mutton-seekh-kabab.jpg' },
  { slug: 'mutton-meat-ball', name: 'Mutton Meat Ball', desc: 'Seasoned mutton formed into flavorful, versatile meatballs.', img: '/images/products/mutton-meat-ball.jpg' },
  { slug: 'mutton-samosa', name: 'Mutton Samosa', desc: 'A triangular pastry filled with succulent mutton and aromatic spices.', img: '/images/products/mutton-samosa.jpg' },
  { slug: 'mutton-cheese-samosa', name: 'Mutton Cheese Samosa', desc: 'Tender mutton, cheese, and spices in a crispy pastry shell.', img: '/images/products/mutton-cheese-samosa.jpg' },
  { slug: 'chicken-tandoori-nuggets', name: 'Chicken Tandoori Nuggets', desc: 'Marinated in tandoori spices for a smoky, spicy flavor.', img: '/images/products/chicken-tandoori-nuggets.jpg' },
  { slug: 'chicken-garlic-finger', name: 'Chicken Garlic Finger', desc: 'A flavorful garlic seasoning for a burst of taste in every bite.', img: '/images/products/chicken-garlic-finger.jpg' },
  { slug: 'chicken-nuggets', name: 'Chicken Nuggets', desc: 'Classic, bite-sized chicken with a crispy coating.', img: '/images/products/chicken-nuggets.jpg' },
  { slug: 'chicken-cheese-nuggets', name: 'Chicken Cheese Nuggets', desc: 'Tender chicken meets a creamy cheese filling.', img: '/images/products/chicken-cheese-nuggets.jpg' },
  { slug: 'tandoori-grill-burger', name: 'Tandoori Grill Burger', desc: 'Tandoori-spiced chicken with fresh toppings in a soft bun.', img: '/images/products/tandoori-grill-burger.jpg' },
  { slug: 'chicken-kheema-paratha', name: 'Chicken Kheema Paratha', desc: 'A flatbread stuffed with flavorful chicken and spices.', img: '/images/products/chicken-kheema-paratha.jpg' },
  { slug: 'mutton-kheema-paratha', name: 'Mutton Kheema Paratha', desc: 'Succulent mutton filling in a crispy paratha.', img: '/images/products/mutton-kheema-paratha.jpg' },
  { slug: 'samosa-patti-nonveg', name: 'Samosa Patti', desc: 'Thin, versatile pastry sheets to create your own samosas.', img: '/images/products/samosa-patti.jpg' },
];
